CREATE DATABASE DBCAFETERIAHCC

USE DBCAFETERIAHCC

CREATE TABLE Tb_HccOrdenes(
OrdId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
MesId INT NOT NULL,
CatordId INT NOT NULL,
ord_fecha_inicio DATE NOT NULL,
ord_estatus TINYINT NOT NULL,
CONSTRAINT FK_MesId FOREIGN KEY (MesId) REFERENCES Tb_HccMesas(MesId),
CONSTRAINT FK_CatordId FOREIGN KEY (CatordId) REFERENCES Tb_HccEstatusOrden(CatordId)
)

CREATE TABLE Tb_HccProductos(
ProId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
AlmId INT NOT NULL,
ProNombre VARCHAR(50) NOT NULL,
ProDescripcion VARCHAR(120) NOT NULL,
ProPrecio DECIMAL(10,4),
ProEstatus TINYINT NOT NULL,
CONSTRAINT FK_AlmId FOREIGN KEY (AlmId) REFERENCES Tb_HccAlmacen(AlmId)
)

CREATE TABLE Tb_HccOrdenesDetalle(
OrddetId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
OrdId INT NOT NULL,
ProId INT NOT NULL,
OrddetCantidad SMALLINT NOT NULL,
OrddetEstatus TINYINT NOT NULL,
CONSTRAINT FK_OrdId FOREIGN KEY (OrdId) REFERENCES Tb_HccOrdenes(OrdId),
CONSTRAINT FK_ProId FOREIGN KEY (ProId) REFERENCES Tb_HccProductos(ProId)
)

CREATE TABLE Tb_HccAlmacen(
AlmId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
AlmCantidad INT NOT NULL,
AlmFechaActualizacion DATE NOT NULL,
AlmEstatus TINYINT NOT NULL,
)

CREATE TABLE Tb_HccEstatusOrden(
CatordId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CatordNombre VARCHAR(50) NOT NULL,
CatordEstatus TINYINT NOT NULL,
)

CREATE TABLE Tb_HccMesas(
MesId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
MesLugares SMALLINT NOT NULL,
MesDisponible TINYINT NOT NULL,
MesEstatus TINYINT NOT NULL,
)
